### ISSUE TITLE
[Module Catalog] ModuleTemplate misses `.spec.version` and `.spec.moduleName`, but includes annotation `operator.kyma-project.io/module-version`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#113]
**Description**

Filip reported that our testing ModuleTemplates for template operator miss the `.spec.version` and `.spec.moduleName` fields.

**Expected result**

`modulectl create` using config:

```yaml
name: kyma-project.io/module/template-operator
version: 1.0.3
# ...
```

Creates ModuleTemplate like:

```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: template-operator-1.0.3
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "template-operator"
  annotations:
    # "operator.kyma-project.io/module-version": "1.0.3"  THIS SHOULD BE GONE
spec:
  version: 1.0.3
  moduleName: template-operator
```

**Actual result**

```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: template-operator-1.0.3
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "template-operator"
  annotations:
    "operator.kyma-project.io/module-version": "1.0.3"  # STILL EXISTS
spec:
  # version MISSING
  # moduleName MISSING
```

**Steps to reproduce**

**Troubleshooting**
