### ISSUE TITLE
Check if we parse yamls correctly

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#143]
**Description**

This is likely an error with old CLI, but we should check if we have the same issue with modulectl.

Telemetry created a ModuleTempalte where default CR starts with `---`, see: https://github.tools.sap/kyma/module-manifests/blob/9012a3d1325e1f21dc8a0fcf94b903bb35fc9e3f/modules/telemetry/experimental/telemetry-default-cr.yaml#L1

```yaml
---
apiVersion: operator.kyma-project.io/v1alpha1
kind: Telemetry
metadata:
  labels:
    app.kubernetes.io/name: telemetry
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: telemetry-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-manager
  name: default
```

This was copied as is into the ModuleTempalte, see: https://github.tools.sap/kyma/kyma-modules/blob/7e5a2eae968a238eaf57f41a1b263dc43425d0c9/experimental/moduletemplate-telemetry.yaml#L16

```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: telemetry-experimental
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "telemetry"
  annotations:
    "operator.kyma-project.io/doc-url": "https://help.sap.com/docs/btp/sap-business-technology-platform/kyma-telemetry-module"
    "operator.kyma-project.io/is-cluster-scoped": "false"
    "operator.kyma-project.io/module-version": "1.32.0-experimental" 
spec:
  channel: experimental
  mandatory: false 
  data:
    ---
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Telemetry
    metadata:
      labels:
        app.kubernetes.io/name: telemetry
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: telemetry-manager
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/created-by: telemetry-manager
      name: default
    
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/module/telemetry
// ...
```

**Expected result**

ModuleTemplate shall not have yaml separators `---`

**Actual result**

ModuleTemplate has yaml separators `---`

**Steps to reproduce**

**Troubleshooting**
