### ISSUE TITLE
Provide modulectl version in the OCM

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/modulectl#246]
**Description**

At the moment, in the published OCM, the provider has a fixed version `v1`

```
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/module/telemetry
      provider: '{"name":"kyma-project.io","labels":[{"name":"kyma-project.io/built-by","value":"modulectl","version":"v1"}]}'
```

**Expected result**

The version should be aligned with the released version

**Actual result**

has a fixed version `v1`

**Steps to reproduce**

**Troubleshooting**
