### ISSUE TITLE
[ModuleCatalog] Support `.spec.resources`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#53]
**Description**

Support the **resources** introduced via https://github.com/kyma-project/lifecycle-manager/issues/1842. The module config file should support a new field that is than written into `.spec.resources`. 

**Reasons**

Support the **resources** field introduced via https://github.com/kyma-project/lifecycle-manager/issues/1842

**Acceptance Criteria**

- [x] When adding entries to `module-config.yaml`
  ```yaml
  resources:
  - name: <string>
    link: <link>
  ```
- [x] Then the entry is written to the generated module template as:
  ```yaml
  spec:
    resources:
     - name: <string>
       link: <link>
  ```
- [x] When adding no entries to `module-config.yaml` resources, then the entry is written to the generated module template as:
  ```yaml
  spec:
    resources:
     - name: rawManifest
       link: <link from manifest field in module-config>
  ```
- [x] There should always be an entry for resources in generated module template
- [x] Validations include
  - [x] `name` must be unique
  - [ ] `link` must be a valid web URL (http* and not file://)

**Attachments**
