### ISSUE TITLE
[ModuleCatalog] Support `.spec.associatedResources`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#54]
**Description**

Support the **associatedResources** introduced via https://github.com/kyma-project/lifecycle-manager/issues/1843. The module config should be extended with a new field that is than written into `.spec.associatedResources`. 

**Reasons**

Support the **associatedResources** field introduced via https://github.com/kyma-project/lifecycle-manager/issues/1843

**Acceptance Criteria**

- [x] When adding entries to `module-config.yaml`
  ```yaml
  associatedResources:
  - group: networking.istio.io
    version: v1alpha3
    kind: gateways
  - group: networking.istio.io
    version: v1alpha3
    kind: virtualservices
  ```
- [x] Then the entry is written to the generated module template as:
  ```yaml
  spec:
    associatedResources:
    - group: networking.istio.io
      version: v1alpha3
      kind: gateways
    - group: networking.istio.io
      version: v1alpha3
      kind: virtualservices
  ```
- [x] If field is not present in moduleconfig file `.spec.associatedResources` should be omitted
- [x] Validations include
  - [x] `group` must be a valid group
  - [x] `version` must be a valid version
  - [x] `kind` must be a valid kind
- [x] Unit test validation
- [x] Adapt e2e tests
- [x] Add new field to scaffold command as commented field

**Attachments**
