### ISSUE TITLE
[ModuleCatalog] Support `.spec.info`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#55]
**Description**

Support the **info** introduced via https://github.com/kyma-project/lifecycle-manager/issues/1841. The module config should be extended with a new field that is than written into `.spec.info`. 

**Reasons**

Support the **info** field introduced via https://github.com/kyma-project/lifecycle-manager/issues/1841

**Acceptance Criteria**

- [ ] When adding entries to `module-config.yaml`
  ```yaml
  info:
    repository: <link>
    documentation: <link>
    icons:
    - name: <string>
      link: <link>
  ```
- [ ] Then the entry is written to the generated module template as:
  ```yaml
  spec:
    info:
      repository: <link>
      documentation: <link>
      icons:
      - name: <string>
        link: <link>
  ```
- [ ] Empty source raises an error (optional in the CRD for compatibility reason, but mandatory in modulectl already)
- [ ] Validations include
  - [ ] type `<link>` must be valid URLs
  - [ ] `name` in `icons` must be unique
- [ ] Add new field to scaffold command as commented field
- [ ] Cover with unit tests
- [ ] Adapt E2E tests to include new fields

**Attachments**
