### ISSUE TITLE
[ModuleCatalog] Support `.spec.manager`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#57]
:construction: field name to be decided, namespace may become optional

**Description**

Support the **manager** introduced via https://github.com/kyma-project/lifecycle-manager/issues/1840. The module config should be extended with a new field that is than written into `.spec.manager`. 

**Reasons**

Support the **manager** field introduced via https://github.com/kyma-project/lifecycle-manager/issues/1840

**Acceptance Criteria**

- [x] Check the correct naming of [`manager` field](https://github.com/kyma-project/lifecycle-manager/issues/1840) and adapt accordingly
- [x] When adding entries to `module-config.yaml`
  ```yaml
  manager:
    group: <group>
    version: <version>
    kind: <kind>
    namespace: <namespace> (optional)
    name: <name>
  ```
- [x] Then the entry is written to the generated module template as:
  ```yaml
  spec:
    manager:
      group: <group>
      version: <version>
      kind: <kind>
      namespace: <namespace>
      name: <name>
  ```
- [x] Empty source leads to nothing written
- [x] Validations in place, share validation code with https://github.com/kyma-project/modulectl/issues/54
- [x] Cover new functionality in unit tests
- [x] Adapt E2E test to cover new fields

**Attachments**
