### ISSUE TITLE
[Mandatory Modules] Introduce mandatory module Label in module create

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/modulectl#94]
**Description**

Whenever create module is executed with module-config's mandatory: true, the resulting ModuleTemplate should also have the mandatory module label: operator.kyma-project.io/mandatory-module

**Reasons**

**AC**

- [x] module config like
  ```yaml
  mandatory: true
  # ...
  ```
- [x] leads to ModuleTemplate like
  ```yaml
  apiVersion: operator.kyma-project.io/v1beta2
  kind: ModuleTemplate
  metadata:
    name: template-operator-1.0.3
    namespace: kcp-system
    labels:
      "operator.kyma-project.io/mandatory-module": "true"
      # ...
  ```
- [x] functionality covered in unit tests
- [x] functionality covered in e2e tests

**Attachments**
